Claro, vou ajudá-lo a criar um arquivo `docker-compose.yml` que cria um banco de dados PostgreSQL local com uma instância de leitura e outra de gravação. Aqui está o arquivo:

```yaml
version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  reader:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    command: ["postgres", "-c", "max_connections=200", "-c", "shared_buffers=256MB"]
    depends_on:
      - db

  writer:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    command: ["postgres", "-c", "max_connections=200", "-c", "shared_buffers=256MB"]
    depends_on:
      - db

```

Este arquivo define três serviços:

- `db`: Cria um contêiner PostgreSQL com uma instância de gravação.
- `reader`: Cria um contêiner PostgreSQL com uma instância de leitura.
- `writer`: Cria outro contêiner PostgreSQL com outra instância de gravação.

Os contêineres `reader` e `writer` dependem do contêiner `db`, que é a instância principal. O contêiner `db` é mapeado para a porta padrão do PostgreSQL (5432) no host. Os contêineres `reader` e `writer` são configurados para se conectarem ao contêiner `db`. Além disso, os contêineres `reader` e `writer` são configurados para terem um número máximo de conexões de 200 e buffers compartilhados de 256 MB.

Espero que isso ajude! Se você tiver alguma dúvida, por favor me avise.

Origem: conversa com o Bing, 06/10/2023
(1) Create a postgres database within a docker-compose.yml file. https://stackoverflow.com/questions/75246059/create-a-postgres-database-within-a-docker-compose-yml-file.
(2) Docker-Compose with PostgreSQL ready to use - GitHub. https://github.com/felipewom/docker-compose-postgres.
(3) Initialize Postgres db in Docker Compose - Stack Overflow. https://stackoverflow.com/questions/56643961/initialize-postgres-db-in-docker-compose.